Feat(Main & Requests Pages) - connection with BE
Dean-Solutions/classes-verifier-fe pull request #13
Opened 2024-04-08 22:35 UTC by jaswiate

na usuwaniu enrollmentow wyrzuca 405
requesty obsłuze jutro po pumach bo juz usypiam

2024-04-11 23:56 UTC, jaswiate commented
Można jako dziekan kliknąć na requescie zatwierdz badz odrzuc i w zaleznosci jaki request zostal wyslany to to sie dzieje
krzyczy o any type ale wydaje mi się ze to przez to ze są pododawane requesty ze swaggera bez nazw przedmiotu itp 
takze fajnie jakby baza moze zostala wyczyszczona i wypełniona na nowo troche mniej losowymi rzeczami

2024-04-12 08:52 UTC, ShockOfficial commented
Brakuje w `package.json` zależności @tanstack/react-query-devtools co będzie powodować problemy. 
Dodaj ją `pnpm add @tanstack/react-query-devtools` i sprwadź czy pojawi ci się wpis w `package.json`
```js
		"@tanstack/react-query": "^5.28.6",
		"@tanstack/react-query-devtools": "^5.29.2",
		"@tanstack/react-table": "^8.14.0",
```

2024-04-12 10:01 UTC, ShockOfficial requested changes

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +	);
Ten `semesterId=1` tutaj rozumiem, jest zahardcodowany ze znanych powodów.
Zostaw to tutaj na razie w taki sposób.  Dodałem na to osobny task https://pepesob.atlassian.net/browse/IO-93

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +	};
```js
	const handleConfirmButton = (
		userId: number,
		subjectId: number,
		semesterId: number,
		enrollStatus: EnrollStatus,
	) => {
		editEnrollment({
			userId,
			subjectId,
			semesterId,
			enrollStatus,
		});
	};
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +	) => {
Rozbić na `handleAddRequest()` oraz `handleRemoveRequest()` -> Unikniemy sytuacji podawania undefined czy null. SOLID -> S

Nie trzeba robić `string | undefined` gdy dajesz optional parameter `subjectIdAdd?: string` 
Poprawnie
` subjectIdAdd?: string`

2024-04-12 10:01 UTC, ShockOfficial commented on src/types/request.types.ts
> +	requestStatus?: string;
dodać tutaj odpowiednie typy statusów. 


Dodaj enum lub typ zamiast stringu
`type RequestStatus = "REJECTED" | "ACCEPTED" ... ... ... `

2024-04-12 10:01 UTC, ShockOfficial commented on src/types/request.types.ts
> +export interface RequestEnroll {
Na pewno wszystko tutaj jest optional?

2024-04-12 10:01 UTC, ShockOfficial commented on src/types/request.types.ts
> +	requestStatus?: string;
Użyć tutaj `RequestStatus` type

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +			addRequest(newRequestAdd);
```js
			addRequest({
				description: t('addSubjectText'),
				submissionDate: currentTime.toISOString(),
				requestType: RequestType.ADD,
				senderId: p.student.userId,
				requestEnrolls: [
					{
						semesterId: semesterId,
						requestStatus: EnrollStatus.PENDING,
						userId: p.student.userId,
						subjectId: parseInt(subjectIdAdd),
					},
				],
			});
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +			addRequest(newRequestDelete);
```js

			addRequest({
				description: requestDescription,
				submissionDate: currentTime.toISOString(),
				requestType: RequestType.DELETE,
				senderId: p.student.userId,
				requestEnrolls: [
					{
						semesterId: semesterId,
						requestStatus: EnrollStatus.PENDING,
						userId: p.student.userId,
						subjectId: subjectIdDelete,
					},
				],
			});
		}
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +						1,
dodaj tutaj `// TODO fix after creating addSemesterModal`

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +			addRequest(newRequestAdd);
Dodaj enum `RequestType` w pliku .types

2024-04-12 10:01 UTC, ShockOfficial commented on src/types/request.types.ts
> +	requestType: string;
Podmień na `RequestType`

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +			addRequest(newRequestDelete);
`RequestType.DELETE`

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +							mih={rem(70)}
nie trzeba `rem()`

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +												enrollment.semester.semesterId,
nie róbmy `selectValue.?charAt(0)` Gdy zmienisz `classNames` to to powinieneś poprawić

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +									}}
To samo co wyżej.

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +		classes?.map(({ name, subjectId }) => `${subjectId} ${name}`) || [];
```js
	const classNames =
		classes?.map(({ name, subjectId }) => ({
			value: subjectId.toString(),
			label: name,
		})) || [];
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +											w={200}
```js
miw={200}
maw={350}
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
>  						sx={(theme) => ({
Stworzyć osobny komponent dla ogólnego Requestu i nadać mu inne style. Wyróżnić go może stroke dashed? Spróbuj coś zaproponować.

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/Classes.tsx
> +													data={classNames}
```js
miw={200}
maw={350}
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
> +
```js
	const studentNames =
		studentData?.map(({ firstName, lastName, indexNumber }) => ({
			value: indexNumber.toString(),
			label: `${firstName} ${lastName} (${indexNumber})`,
		})) || [];
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
> +												value={nameIndexInput}
```js
  data={studentNames.filter(
    (name) =>
      !classStudents.enrollments.some(
        ({ user: { indexNumber } }) =>
          indexNumber === name.value,
      ),
  )}
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
>  	];
Poza kod komponentu

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
> +export const ClassesDean = (p: ClassesDeanProps) => {
```js

export const ClassesDean = ({ semesterTag }: ClassesDeanProps) => {

```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
> +
```js
	const handleTrashButton = (
		userId: number,
		subjectId: number,
		semesterId: number,
		enrollStatus: EnrollStatus,
	) => {
		editEnrollment({
			userId: userId,
			subjectId: subjectId,
			semesterId: semesterId,
			enrollStatus: enrollStatus,
		});
	};
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
> +	};
```js
	const handleStudentForm = () => {
		const student = studentData?.find(
			(item) => item.indexNumber === nameIndexInput.split(' ').pop(),
		);
		if (student) {
			addEnrollment({
				userId: student.userId,
				subjectId: parseInt(openedClass || ''),
				semesterId: 1, // TODO ...
				enrollStatus: EnrollStatus.PROPOSED,
			});
		}
	};
```

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Classes/ClassesDean.tsx
> +							mih={rem(70)}
`mih={70}`

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Requests/RequestsDean.tsx
> +				requestEnrollId: requestEnrollId,
Zastosować taki sam kod jak wyżej. (Nie rozdrabnaić na obiektu, które potem przesyłasz - duży mess się robi w kodach komponentu)

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Requests/RequestsDean.tsx
> +		if (status === 'REJECTED') {
Statusy powinny być zgodne z tym typem co dodasz

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Requests/RequestsDean.tsx
> +				requestType: 'ACCEPT',
Typ.

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Requests/RequestsDean.tsx
> +														re.requestEnrollId,
typ

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Requests/RequestsStudent.tsx
> +	console.log(userRequests);
Delete

2024-04-12 10:01 UTC, ShockOfficial commented on src/components/Requests/RequestsStudent.tsx
> +	const { data: userRequests } = useGetUserRequests(4);
Dodać  komentarz TODO

2024-04-12 10:01 UTC, ShockOfficial commented on src/pages/_app.tsx
> +				<ReactQueryDevtools />
Delete

2024-04-12 10:01 UTC, ShockOfficial commented on src/query/classes.query.ts
> +		staleTime: 100,
Zwiększ staleTime

2024-04-12 10:01 UTC, ShockOfficial commented on src/query/request.query.ts
> +		enabled: true,
nie potrzebne enabled

2024-04-12 10:01 UTC, ShockOfficial commented on src/query/request.query.ts
> +		enabled: true,
nie potrzebne enabled

2024-04-12 10:01 UTC, ShockOfficial commented on src/query/students.query.ts
> +		enabled: true,
nie potrzebne enabled

2024-04-12 10:01 UTC, ShockOfficial commented on src/services/enrollment.service.ts
> +	}
Chyba tak lepiej? Sprawdź czy zadziała tak jak trzeba
```js
	const statuses = enrollStatuses
		? `&statuses=${enrollStatuses.join(',')}`
		: '';

```

2024-04-12 10:01 UTC, ShockOfficial commented on src/services/enrollment.service.ts
> +	}
Również czemu enrollStatuses możę być undefined?

2024-04-12 10:01 UTC, ShockOfficial commented on src/services/request.service.ts
> +	console.log(userRequest);
remove

2024-04-12 10:01 UTC, ShockOfficial commented on src/services/request.service.ts
> +	console.log(userRequest);
remove

2024-04-12 10:01 UTC, ShockOfficial commented on src/utils/colors.util.ts
> +export const getColor = (status: string | undefined) => {
Użyć odpowiedniego typu

2024-04-15 09:56 UTC, ShockOfficial requested changes

2024-04-15 09:56 UTC, ShockOfficial commented on src/types/request.types.ts
> +	requestStatus?: string;
Tutaj nie zostało podmienione na `RequestStatus`

2024-04-15 09:56 UTC, ShockOfficial commented on src/services/enrollment.service.ts
> +
nadal nie wiem czemu tutaj robisz `%2C` zamiast po prostu `,`
Wydaje mi się, że next powinien ogarnąć i sam zamienić `,` na `%2C` a nawet jeśli nie to niżej przy budowaniu linku możesz dać `encodeURIComponent()`

2024-04-15 09:56 UTC, ShockOfficial commented on src/services/enrollment.service.ts
> +		: '';
To samo. CTRL+C/V
nadal nie wiem czemu tutaj robisz `%2C `zamiast po prostu `,`
Wydaje mi się, że next powinien ogarnąć i sam zamienić `,` na`%2C` a nawet jeśli nie to niżej przy budowaniu linku możesz dać `encodeURIComponent()`

2024-04-15 09:56 UTC, ShockOfficial commented on src/query/enrollment.query.ts
>  		enabled: true,
Delete

2024-04-16 07:36 UTC, ShockOfficial approved these changes

2024-04-16 10:12 UTC, merged